import type { ErrorCode, ServerError } from "./lobby.ts";

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  ROOM_NOT_FOUND: "That room is gone or the code is incorrect.",
  ROOM_FULL: "Every spot is taken, including spots held for reconnecting friends.",
  INVALID_ROOM_CODE: "Use the five-character code your friend shared.",
  INVALID_DISPLAY_NAME: "Use 2–20 letters, numbers, spaces, or simple name punctuation.",
  NAME_TAKEN: "Someone in this room already has that name. Pick another.",
  GAME_ALREADY_STARTED: "That game has already started.",
  NOT_HOST: "Only the current host can do that.",
  PLAYER_NOT_FOUND: "Your room membership could not be found.",
  INVALID_SESSION: "Your saved session is no longer valid. Join again to get a new spot.",
  SESSION_ACTIVE: "You already have a spot. Return to your room or leave it first.",
  SESSION_REPLACED: "Your session was opened in another tab. This tab can no longer act for that player.",
  SESSION_EXPIRED: "Your reconnect window ended. Join again to get a new spot.",
  ROOM_EXPIRED: "This room closed after being inactive. Create or join a new one.",
  RATE_LIMITED: "A little too fast. Wait a moment and try again.",
  INVALID_PAYLOAD: "That request could not be understood. Refresh and try again.",
  SETTINGS_CONFLICT: "Make room for everyone: the limit cannot be lower than the occupied spots.",
  REQUEST_CONFLICT: "That request was already used for a different action.",
  SERVER_ERROR: "Something went wrong on the server. Try again shortly.",
  SERVER_BUSY: "The server is full right now. Try again shortly.",
  CONNECTION_LOST: "The server could not be reached. Check your connection and try again.",
  ROOM_LOCKED: "This room is locked. Existing players can reconnect, but new joins are closed.",
  PASSWORD_REQUIRED: "This room needs a password. Ask the host and enter it below.",
  INCORRECT_PASSWORD: "Incorrect room password. Check with the host and try again.",
  INVALID_PASSWORD: "Use 8–64 password characters, with at least 8 non-edge-space characters.",
  SECURITY_CHANGED: "Room security changed while you were joining. Please try again.",
  INVALID_ROOM_NAME: "Use 2–40 letters, numbers, spaces, or simple punctuation for the room name.",
  PLAYER_REMOVED: "You were removed from the room.",
  INVALID_TARGET: "That player is not available for that action.",
  COLOR_UNAVAILABLE: "That color is taken, including reconnecting players. Choose another.",
  SPECTATORS_FULL: "All eight spectator spots are taken, including reconnect reservations.",
  PLAYER_ONLY: "That action is for active players, not spectators.",
  HOST_MUST_TRANSFER: "Transfer host to another player before becoming a spectator.",
  INVALID_CHAT: "Write 1–280 characters. Empty messages and control characters are not allowed.",
  INVALID_REPORT: "Choose a report reason and keep the optional description to 240 characters.",
  REPORT_ALREADY_SENT: "You already reported this player recently. Please wait before reporting again.",
  NOT_READY: "Four to ten connected active players must all be ready before the game can start.",
  ROUND_NOT_PREPARED: "There is no prepared Secret Rule round for that action.",
  INVALID_GAME_PHASE: "That action is not available during this part of the round.",
  ACTION_REJECTED: "That game action was not accepted.",
  NOT_YOUR_TURN: "Wait for your turn before playing.",
  CARD_NOT_FOUND: "That card is not in your current hand.",
  CHALLENGE_CLOSED: "The challenge window has already closed.",
  CHOICE_REQUIRED: "Finish your private game choice before play can continue.",
  VOTE_ALREADY_CAST: "Your vote for this target decision is already locked.",
  BASIC_ACTION_UNAVAILABLE: "The Basic Button action is available only when normal card play is exhausted.",
};

export function protocolError(code: ErrorCode): ServerError {
  return { code, message: ERROR_MESSAGES[code], recoverable: !["INVALID_SESSION", "SESSION_EXPIRED", "SESSION_REPLACED", "ROOM_EXPIRED", "PLAYER_REMOVED"].includes(code) };
}
